### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by rtmlp** [Eiqnepm/portcheck#1]
Hi,

I have using portcheck as per the docker-compose instructions available in the `readme.md` file. However, in the container logs for portcheck, I noticed the following

```
stderr 19:24:10 dial tcp ip_address:port_numbre: connect: connection refused
stderr 19:24:11 Post "http://localhost:8090/api/v2/auth/login": dial tcp 127.0.0.1:8090: connect: connection refused
```

I also want to point out that port forwarding issue seems to have resolved after using `portcheck`. Thanks for building this

**Comment by eiqnepm** [comment]
May you send your Docker Compose contents with any sensitive information redacted so I can assess your specific configuration?

**Comment by rtmlp** [comment]
Hi. I have uploaded the code at this [link](https://pastecode.io/s/bubyekwc) on pastecode

**Comment by eiqnepm** [comment]
Do the errors happen every five minutes, or just once when the container is initially started?

**Comment by rtmlp** [comment]
I checked the error logs from the past two days. They have twice `07/29 19:14 hrs` and `07/31 07:10 hrs`. Does anything in the config seems incorrect. Thanks for taking a look at this

**Comment by rtmlp** [comment]
I restarted the container again and I noticed the same logs for the container.

**Comment by eiqnepm** [comment]
If you start Gluetun and qBittorrent at the same time, this is to be expected, because portcheck will most likely start monitoring the port before Gluetun and qBittorrent have had time to initialize.

If it only happens once when the container is started, everything is working as expected, if it happens every time it checks the port, which is five minute by default, then you have an issue.

**Comment by rtmlp** [comment]
Thanks for the clarification. Checked the logs and can confirm that it is only happening during the restart. Hence closing the issue
